version: 2.1
jobs:
  build:
    docker:
      - image: 455589372314.dkr.ecr.eu-central-1.amazonaws.com/omnia-srv-base:0.0.2
        aws_auth:
          aws_access_key_id: $AWS_SANDBOX_USERNAME  # can specify string literal values
          aws_secret_access_key: $AWS_SANDBOX_PASSWORD  # or project UI envar reference
    working_directory: ~/basecode
    steps:
      - checkout
      - run: ls -lah
      - run: npm install
      - run: aws --version
      - run: aws s3 sync . s3://octopus-test
      - run: zip -r omnia-sample.1.0.$CIRCLE_BUILD_NUM.zip ./*
      - run: lss -lah
      - run:
         name: Install jFrog CLI
         command: curl -fL https://getcli.jfrog.io | sh
      - run:
         name: Push to Artifactory
         command: |
           ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
           ./jfrog rt u omnia-sample.1.0.$CIRCLE_BUILD_NUM.zip artifactory-build-info --build-name=omnia-sample.1.0.$CIRCLE_BUILD_NUM.zip --build-number=$CIRCLE_BUILD_NUM
           ./jfrog rt bce omnia-sample.1.0.$CIRCLE_BUILD_NUM.zip $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
           ./jfrog rt bp omnia-sample.1.0.$CIRCLE_BUILD_NUM.zip $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory

workflows:
  commit:
    jobs:
      - build
